openapi: 3.0.3
info:
  title: Hello API
  version: 1.0.0
  description: Simple Hello World API
paths:
  /hello:
    get:
      summary: Returns a greeting
      operationId: getHello
      tags:
        - hello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
          example: "Hello, World!"
